const StorageConstants = {
    FAILED_SIGNUP_EMAIL_EXIST: "FAILED_SIGNUP_EMAIL_EXIST",
    FAILED_LOGIN_EMAIL_NOT_FOUND: "FAILED_LOGIN_EMAIL_NOT_FOUND",
    FAILED_LOGIN_PASSWORD: "FAILED_LOGIN_PASSWORD",
    FAILED_GET_USER: "FAILED_GET_USER",
    SUCCESS_SIGNUP: "SUCCESS_SIGNUP",
    SUCCESS_LOGIN: "SUCCESS_LOGIN",
    SUCCESS_STORE_USER: "SUCCESS_STORE_USER",
    SUCCESS_GET_USER: "SUCCESS_GET_USER",
    SUCCESS_SET_SESSION: "SUCCESS_SET_SESSION",
    SUCCESS_LOGOUT: "SUCCESS_LOGOUT",
    UNEXPECTED_MULTIPLE_USERS: "UNEXPECTED_MULTIPLE_USERS",
    UNEXPECTED_SIGNUP_ERROR: "UNEXPECTED_SIGNUP_ERROR",
    UNEXPECTED_LOGIN_ERROR: "UNEXPECTED_LOGIN_ERROR",
    UNEXPECTED_STORE_USER: "UNEXPECTED_STORE_USER",
    UNEXPECTED_SET_SESSION: "UNEXPECTED_SET_SESSION",
    UNEXPECTED_GET_USER: "UNEXPECTED_GET_USER",
    UNEXPECTED_LOGOUT: "UNEXPECTED_LOGOUT",
    USERS: "USERS",
    USER_AUTH: "USER_AUTH"
}

export default StorageConstants;